### ISSUE TITLE
View navigation

### ISSUE THREAD

**Issue by amay077** [anaisbetts/starter-mobile#11]
I added code for navigating to "SecondViewController" in starter-ios.
Follow the code: (via https://github.com/reactiveui/ReactiveUI/blob/5.0.1/MobileSample-WinRT/ViewModels/TestPage1ViewModel.cs)

TestViewModel.cs:

```
public IReactiveCommand NavPage2 { get; protected set; }

public TestViewModel(IScreen screen)
{
    TheGuid = Guid.NewGuid().ToString();

    HostScreen = screen ?? RxApp.DependencyResolver.GetService<IScreen>();
    NavPage2 = HostScreen.Router.NavigateCommandFor<SecondViewModel>();
}
```

But I have a problem in `TestViewController`.
How can I get `IScreen` when create `TestViewModel`?

TestViewController.cs:

```
public override async void ViewDidLoad()
{
    base.ViewDidLoad();
    this.OneWayBind(ViewModel, x => x.TheGuid, x => x.TheGuid.Text);
    ViewModel = await BlobCache.LocalMachine.GetOrCreateObject("TestViewModel", () => {
        return new TestViewModel( /* How to get IScreen?*/ );
    });
}
```

Any idea?

**Comment by anaisbetts** [comment]
> How can I get IScreen when create TestViewModel

iOS and Android don't really use ViewModel-based navigation so this pattern doesn't apply well. Stick with the establish patterns on the OS

**Comment by amay077** [comment]
Thank you for reply.
I got it.
