### ISSUE TITLE
'.' in iOS project names.

### ISSUE THREAD

**Issue by nverinaud** [anaisbetts/starter-mobile#4]
> NOTE: Don't use a '.' in any of your project names, iOS gets hella upset. Yes, I think 
> it'd look way better than '-' too.

I didn't experienced any issues, could you be more explicit ? (May I need to drop my current '.' projects... :worried: ?)

**Comment by anaisbetts** [comment]
@nverinaud If it works for you that's fine, but Xamarin.iOS will continually try to rename my project and break things in the process when I did this, and I also got a failure when I tried to deploy to device

**Comment by nverinaud** [comment]
Okay, I'll try that again. I have encoutnered an issue when I used a dash for the project's name. Bad namespaces and iOS project build error, because he wants an alphabetical name for the final executable. Easy to fix though.
