### ISSUE TITLE
AOT problem with Akavache.Sqlite3.dll

### ISSUE THREAD

**Issue by nverinaud** [anaisbetts/starter-mobile#7]
I encounter a problem when trying to build **for the device** with the following error :

```
Error MT3001: Could not AOT the assembly '/Users/nicolas/Developement/Xamarin/Protos/starter-mobile/TestResolver-iOS/obj/iPhone/Debug/mtouch-cache/Build/Akavache.Sqlite3.dll' (MT3001)
```

**Comment by anaisbetts** [comment]
Are you using the Alpha channel? If not, try switching to it

**Comment by nverinaud** [comment]
Does not work with Debug mode for Device.

**Comment by stefanfisk** [comment]
I am also seeing this. It seems like building only works for the simulator.

I'm running the Alpha channel.

**Comment by anaisbetts** [comment]
@nverinaud This is fixed in the newest Akavache, you probably need to bump the submodule version for starter-mobile
